# Generated by Django 2.2.5 on 2020-11-12 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('country_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('state_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('district_name', models.CharField(max_length=100, null=True)),
                ('state_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.State')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('country_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
                ('district_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.District')),
                ('state_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.State')),
            ],
        ),
    ]
