# Generated by Django 2.2.5 on 2020-11-12 05:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place_your_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Company_name', models.CharField(max_length=100)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('State', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Landmark', models.CharField(max_length=100, null=True)),
                ('Pincode', models.IntegerField(null=True)),
                ('Sanitizer', models.IntegerField(null=True)),
                ('Hand_gloves', models.IntegerField(null=True)),
                ('Mask', models.IntegerField(null=True)),
                ('Thermometer', models.IntegerField(null=True)),
                ('PPE_kit', models.IntegerField(null=True)),
            ],
        ),
    ]
