# Generated by Django 2.2.5 on 2020-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='Tracking_details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='Tracking_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
