# Generated by Django 2.2.5 on 2020-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Enter_Triglycerides_in_mg_dl', models.IntegerField(null=True)),
                ('Select_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
