# Generated by Django 2.2.5 on 2020-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_tracker',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
