# Generated by Django 2.2.5 on 2020-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_tracker', '0002_health_tracker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_tracker',
            name='Select_Date',
            field=models.DateField(null=True),
        ),
    ]
