# Generated by Django 2.2.5 on 2020-11-15 11:03

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('consulation', models.CharField(max_length=100, null=True)),
                ('scan', models.CharField(max_length=100, null=True)),
                ('profile_for', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=10)),
                ('email', models.CharField(max_length=20, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('payment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('scan_center_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('business_start', models.CharField(max_length=100, null=True)),
                ('no_of_employee', models.IntegerField(null=True)),
                ('work_days', models.IntegerField(null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('landline_no', models.IntegerField(null=True)),
                ('lab_email', models.CharField(max_length=100, null=True)),
                ('lab_url', models.CharField(max_length=100, null=True)),
                ('lab_logo', models.ImageField(blank=True, upload_to='images/')),
                ('lab_image', models.ImageField(blank=True, upload_to='images/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('service_provider', models.CharField(max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('scan_name', models.CharField(choices=[('Xray', 'Xray'), ('Ultra Sound', 'Ultra Sound'), ('CT', 'CT'), ('PET', 'PET'), ('MRI', 'PET'), ('EUS', 'EUS'), ('Bne Densitometry(DEXA)', 'Bne Densitometry(DEXA)'), ('Fluoroscopy', 'Fluoroscopy'), ('Mammography', 'Mammography')], max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('scan_test_list', models.TextField(null=True)),
                ('google_location', models.CharField(max_length=100, null=True)),
                ('about_lab_description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('scan_package_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
