# Generated by Django 2.2.5 on 2020-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('What_do_you_need_the_service', models.CharField(choices=[('Immediately', 'Immediately'), ('In the next 3 days', 'In the next 3 days'), ('In the next 7 days', 'In the next 7 days'), ('In the next 15 days', 'In the next 15 days'), ('After a month', 'After a month')], max_length=100, null=True)),
                ('What_type_of_service_do_you_need', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time-Non-Live-in', 'In the next 3 days'), ('Full Time-Live-in', 'In the next 7 days')], max_length=100, null=True)),
                ('Select_the_preferred_gender_of_the_homenurse', models.CharField(choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('what_are_the_requirement_for_the_service', models.CharField(choices=[('Post operative assistance', 'Post operative assistance'), ('Administration injuctions', 'Administration injuctions'), ('Monitoring vitals', 'Monitoring vitals'), ('Daily Assistance', 'Daily Assistance'), ('Mobility Assistance', 'Mobility Assistance'), ('Feeding and Making meals', 'Feeding and Making meals'), ('Others', 'Others')], max_length=100, null=True)),
                ('For_whom_do_you_need_service', models.CharField(choices=[('Elder Parents', 'Elder Parents'), ('Grand Parents(Senior Citizens)', 'Grand Parents(Senior Citizens)'), ('Relatives', 'Relatives'), ('Friend', 'Friend'), ('Self', 'Self')], max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
