# Generated by Django 2.2.5 on 2020-11-15 10:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toll_Free_Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('Comment', models.CharField(max_length=100, null=True)),
                ('Count', models.IntegerField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
