# Generated by Django 2.2.5 on 2020-11-12 05:32

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Category_type', models.CharField(choices=[('Drug Addiction Clinic', 'Drug Addiction Clinic'), ('STD Clinic', 'STD Clinic'), ('Nutrition Clinic', 'Nutrition Clinic'), ('Baby Clinic', 'Baby Clinic'), ('Urgent & Emergency Care Clinic', 'Urgent & Emergency Care Clinic'), ('Male Fertlity Clinic', 'Male Fertlity Clinic'), ('Female Fertlity Clinic', 'Female Fertlity Clinic'), ('Baby Adoption', 'Baby Adoption'), ('Poly Clinic', 'Poly Clinic')], max_length=100, null=True)),
                ('Clinic_name', models.CharField(max_length=100, null=True)),
                ('Clinic_url', models.CharField(max_length=100, null=True)),
                ('Clinic_image', models.ImageField(blank=True, upload_to='images/')),
                ('Contact_person', models.CharField(max_length=100, null=True)),
                ('About_clinic', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=20)),
                ('image_alt_tag', models.CharField(max_length=20, null=True)),
                ('video_upload', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=20, null=True)),
                ('video_alt_tag', models.CharField(max_length=20, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('clinic_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('About_clinic', models.CharField(max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
