# Generated by Django 2.2.5 on 2020-11-15 11:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_lab_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('profile_for', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('package', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('image_url', models.CharField(max_length=20, null=True)),
                ('image_alt_tag', models.CharField(max_length=20, null=True)),
                ('video_url', models.CharField(max_length=20, null=True)),
                ('video_alt_tag', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('package_name', models.CharField(max_length=100, null=True)),
                ('package_url', models.CharField(max_length=100, null=True)),
                ('package_image', models.ImageField(blank=True, upload_to='images/')),
                ('package_image_url', models.CharField(max_length=100, null=True)),
                ('image_alt_tag', models.CharField(max_length=20, null=True)),
                ('video_upload', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=20, null=True)),
                ('video_alt_tag', models.CharField(max_length=20, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('lab_name', models.CharField(max_length=100, null=True)),
                ('business_start', models.CharField(max_length=100, null=True)),
                ('no_of_employee', models.IntegerField(null=True)),
                ('work_days', models.IntegerField(null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('landline_no', models.IntegerField(null=True)),
                ('lab_email', models.CharField(max_length=100, null=True)),
                ('lab_url', models.CharField(max_length=100, null=True)),
                ('lab_logo', models.ImageField(blank=True, upload_to='images/')),
                ('lab_logo_url', models.CharField(max_length=100, null=True)),
                ('lab_image', models.ImageField(blank=True, upload_to='images/')),
                ('lab_image_url', models.CharField(max_length=100, null=True)),
                ('lab_alt_image', models.CharField(max_length=100, null=True)),
                ('lab_logo_alt_tag', models.CharField(max_length=20, null=True)),
                ('video_upload', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=20, null=True)),
                ('video_alt_tag', models.CharField(max_length=20, null=True)),
                ('service_provider', models.CharField(max_length=100, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('package_test_list', models.TextField(null=True)),
                ('about_lab_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_profile.Package')),
            ],
        ),
    ]
