# Generated by Django 2.2.5 on 2020-11-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_country_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('country_code', models.IntegerField(null=True)),
                ('country_flag', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_country_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('country_code', models.IntegerField(null=True)),
                ('country_flag', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
