# Generated by Django 2.2.5 on 2020-11-12 05:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_side_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('category_name', models.CharField(choices=[('firstside', 'firstside'), ('secondside', 'secondside')], max_length=20)),
                ('banner_images', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_carts_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('home_slider', models.ImageField(blank=True, upload_to='')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pick_opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Special_care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='settings.Post')),
            ],
        ),
    ]
