# Generated by Django 2.2.5 on 2020-11-12 05:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_url', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('short_description', models.TextField(null=True)),
                ('full_description', models.TextField(null=True)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('video_alt_tag', models.CharField(max_length=100, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Awarenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_url', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('video_alt_tag', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('blog_category', models.CharField(max_length=100, null=True)),
                ('blog_name', models.CharField(max_length=100, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('title_url', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('video_alt_tag', models.CharField(max_length=100, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('cus_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('User_name', models.CharField(max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offers_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('offers_name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_alt_tag', models.CharField(max_length=100, null=True)),
                ('promo_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Processing ', 'Processing')], max_length=100, null=True)),
                ('item', models.CharField(max_length=100, null=True)),
                ('shipping_address', models.CharField(max_length=100, null=True)),
                ('billing_address', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=100, null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('video', models.FileField(blank=True, upload_to='videos/')),
                ('video_url', models.CharField(max_length=100, null=True)),
                ('video_alt_tag', models.CharField(max_length=100, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=100, null=True)),
                ('meta_description', models.TextField(null=True)),
            ],
        ),
    ]
