# Generated by Django 2.2.5 on 2020-11-12 05:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=20)),
                ('qualification', models.CharField(max_length=20, null=True)),
                ('speciality', models.CharField(max_length=20, null=True)),
                ('doctor_image', models.ImageField(blank=True, upload_to='images/')),
                ('doctor_image_url', models.CharField(max_length=20, null=True)),
                ('doctor_alt_image', models.CharField(max_length=20, null=True)),
                ('clinic_name', models.CharField(max_length=20, null=True)),
                ('about_clinic', models.TextField(null=True)),
                ('clinic_image', models.ImageField(blank=True, upload_to='images/')),
                ('clinic_image_url', models.CharField(max_length=20, null=True)),
                ('clinic_alt_image', models.CharField(max_length=20, null=True)),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('working_days', models.CharField(max_length=20, null=True)),
                ('morning_timing', models.CharField(max_length=20, null=True)),
                ('evening_timing', models.CharField(max_length=20, null=True)),
                ('google_location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=10)),
                ('qualification', models.CharField(max_length=20, null=True)),
                ('speciality', models.CharField(max_length=20, null=True)),
                ('doctor_image', models.ImageField(blank=True, upload_to='images/')),
                ('clinic_name', models.CharField(max_length=20, null=True)),
                ('about_clinic', models.TextField(null=True)),
                ('clinic_image', models.ImageField(blank=True, upload_to='images/')),
                ('street_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('working_days', models.CharField(max_length=20, null=True)),
                ('morning_timing', models.CharField(max_length=20, null=True)),
                ('evening_timing', models.CharField(max_length=20, null=True)),
                ('google_location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=10)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_of_doctor_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('consulation', models.CharField(max_length=100, null=True)),
                ('patient_name', models.CharField(max_length=100, null=True)),
                ('profile_for', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Transgender', 'Transgender')], max_length=10)),
                ('email', models.CharField(max_length=20, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('payment', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
