# Generated by Django 2.2.5 on 2020-11-12 05:32

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('hospital_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('payment', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('hospital_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('image_alt_tag', models.CharField(max_length=20, null=True)),
                ('doctor_image_url', models.CharField(max_length=100, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=100, null=True)),
                ('meta_keyword', models.CharField(max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(null=True)),
                ('hospital_type', models.CharField(max_length=100)),
                ('hospital_url', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('image_alt_tag', models.CharField(max_length=20, null=True)),
                ('doctor_image_url', models.CharField(max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_description', models.CharField(max_length=100, null=True)),
                ('meta_keyword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
